version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: trocme
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD:

    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3336:3336
volumes:
  db_data:
